# Generated by Django 5.2.7 on 2025-11-15 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "preferred_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dashiki", "Dashiki Style"),
                            ("kaftan", "Kaftan Style"),
                            ("agbada", "Agbada Style"),
                            ("boubou", "Boubou Style"),
                            ("kente", "Kente Inspired"),
                            ("ankara", "Ankara Pattern"),
                            ("mudcloth", "Mudcloth Design"),
                            ("traditional", "Traditional African"),
                            ("modern_african", "Modern African Fusion"),
                            ("crochet_traditional", "Traditional Crochet"),
                            ("crochet_modern", "Modern Crochet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("ready", "Ready for Pickup/Delivery"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipping_address", models.TextField()),
                ("shipping_city", models.CharField(max_length=100)),
                ("shipping_country", models.CharField(max_length=100)),
                ("shipping_postal_code", models.CharField(max_length=20)),
                ("special_instructions", models.TextField(blank=True)),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="products.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "african_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dashiki", "Dashiki Style"),
                            ("kaftan", "Kaftan Style"),
                            ("agbada", "Agbada Style"),
                            ("boubou", "Boubou Style"),
                            ("kente", "Kente Inspired"),
                            ("ankara", "Ankara Pattern"),
                            ("mudcloth", "Mudcloth Design"),
                            ("traditional", "Traditional African"),
                            ("modern_african", "Modern African Fusion"),
                            ("crochet_traditional", "Traditional Crochet"),
                            ("crochet_modern", "Modern Crochet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Cotton, Wool, Silk blend",
                        max_length=255,
                    ),
                ),
                (
                    "colors_available",
                    models.JSONField(
                        default=list, help_text="List of available colors"
                    ),
                ),
                (
                    "sizes_available",
                    models.JSONField(default=list, help_text="List of available sizes"),
                ),
                (
                    "primary_image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_gallery",
                    models.JSONField(
                        default=list, help_text="Additional product images"
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "is_custom_order",
                    models.BooleanField(default=False, help_text="Made to order item"),
                ),
                (
                    "estimated_delivery_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Days for delivery"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cultural_significance",
                    models.TextField(
                        blank=True, help_text="Cultural meaning or history"
                    ),
                ),
                ("care_instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("size", models.CharField(blank=True, max_length=10)),
                ("color", models.CharField(blank=True, max_length=50)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("custom_measurements", models.JSONField(blank=True, default=dict)),
                ("custom_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
